### PR TITLE
Initial refactoring of reportcity

### LINKED ISSUE #385: Convert sql to ibis-expression on ReportCity
# Objetivos / Objectivos / Purpose

## Geral / General

* Converter o code de dbdata e views para ibis-espression.
* Optimize code readability.
* Optimize reports time reload.

## Específicos / Specific
* Resolver conflito de pd.merge:
```
Exception Type: | MergeError
Can only pass argument "on" OR "left_index" and "right_index", not a combination of both.
```

### PR DESCRIPTION
**Pull request by esloch**
- Closes #385
- Change climate charts, refers in #435.

### CODE REVIEW

**Comment by esloch** [comment]
- Reportcity loading:
    */report/RJ/3304557/202127*
    ``` 
    NEW IBIS
    24 requests
    16.83 MB / 4.96 MB transferred
    Finish: 6.69 s
    DOMContentLoaded: 6.09 s
    load: 6.65 s
    
    SQL
    35 requests
    20.66 MB / 8.01 MB transferred
    Finish: 16.18 s
    DOMContentLoaded: 15.16 s
    load: 16.09 s
    ```

**Comment by fccoelho** [comment]
@esloch Ibis has improved the situation but this is still a lot of data to transfer. We need to look carefully into the logic of the requests to see if we can simplify the requests.

**Comment by esloch** [comment]
> @esloch Ibis has improved the situation but this is still a lot of data to transfer. We need to look carefully into the logic of the requests to see if we can simplify the requests.
> 
> I saw that you have simplified the code a lot, and that is good. But need to look deeper into these loading statistics, and find out how costly is each request so that we can focus our attention on the parts that can give us more savings.
> 
> For example of those 24 requests in the IBIS code, which one is the most time consuming? Which one moves more data?

``` 
 [ I ] Get dengue data from Historico_alerta table in 0.0151 seconds
 [ II ] Filter by geocode and year_week and rename columns for dengue disease in 0.0080 seconds
 [ I ] Get chikungunya data from Historico_alerta_chik table in 0.0152 seconds
 [ II ] Filter by geocode and year_week and rename columns for chikungunya disease in 0.0026 seconds
 [ I ] Get zika data from Historico_alerta table in 0.0002 seconds
 [ II ] Filter by geocode and year_week and rename columns for zika disease in 0.0019 seconds
 [ III ] Obtain all dataframes for views  0.2387 seconds
 [ IIII ] Fetch data from regional_health (regional_saude) and create incidence, climate and tweets charts for all diseases 0.8543 seconds
 ``` 
 As soon as I have the queries for the new **parameter table** for climatechart, I'll test a bench in unittests.

**Comment by fccoelho** [comment]
Perhaps the query from `regional_saude` could be turned into a materialized view.

**Comment by esloch** [comment]
@claudia-codeco and @fccoelho, I'm search for a way to overlap the threshold lines...
new_cliamate_chart_20220329_161528

**Pull request merged**
