### PR TITLE
Add semantic release

### LINKED ISSUE #573: Add version control system

### PR DESCRIPTION
**Pull request by esloch**
Closes #573.

### CODE REVIEW

**Comment by esloch** [comment]
I don't see the need to publish AlertaDengue as a package on PyPi, but for the purposes of version generation using semantic-release it seems necessary.
What did you say @fccoelho ?

**Comment by esloch** [comment]
> I don't see the need to publish AlertaDengue as a package on PyPi, but for the purposes of version generation using semantic-release it seems necessary. What did you say @fccoelho ?

ping @xmnlab.

**Comment by xmnlab** [comment]
Yep that makes sense

**Comment by fccoelho** [comment]
I agree as well.

**Review by fccoelho — APPROVED** [review]

**Pull request closed without merging**
