### PR TITLE
Multi city

### PR DESCRIPTION
**Pull request by fccoelho**
The branch multi-city has reach the minimum functionality to consider a merge into the master branch.
There are still some minor issues to be sorted out  in the interface. These issues should be deocumented in this PR
In order to run  in dev mode, it requires an ssh tunnel to the production database.

### CODE REVIEW

**Comment by fccoelho** [comment]
@flavioamieiro , see if you can run the site running in the  dev-server, we can then start to go over the remaining issues. This is a huge PR, so it's best that we give it a thorough usability test before deciding on a Merge.

**Comment by flavioamieiro** [comment]
@fccoelho , I managed to run it in a development environment and everything ran OK (using python 3 and a SSH tunnel to our server). In a first look, I noticed only three things: 

- `manage.py` said there are unapplied migrations (using BON027's server), this may be a problem. Were there any changes in the model that didn't make it to the database yet?
- The initial load is pretty slow. But this is probably due to the fact that I am using the development server, and there are a lot of AJAX requests at the same time. Since the dev server only answers one at a time, it is always going to be a lot slower than the production environment.
- I noticed we're using decouple but there is no `settings.ini` example. This would be useful for someone running the project for the first time.

I'll keep trying it out and will also try to read the changes. Since there are a lot of changes, this may take some time.

**Comment by fccoelho** [comment]
perhaps we should drop the models completely. they are a remnant of the
firt versio of the site in which we used Geodjango to handle maps and other
information. This is no longer in use, I try to remove it from this branch
and make a new commit.
The speed is really due to to the dev server. Do you think you can put
together a docker container similar to the on in production in which we
could  test the site locally with the same configuration of the production
server?

On Mon, Feb 15, 2016 at 11:09 AM, Flávio Amieiro <notifications@github.com>
wrote:

> @fccoelho <https://github.com/fccoelho> , I managed to run it in a
> development environment and everything ran OK (using python 3 and a SSH
> tunnel to our server). In a first look, I noticed only three things:
>
>    - manage.py said there are unapplied migrations (using BON027's
>    server), this may be a problem. Were there any changes in the model that
>    didn't make it to the database yet?
>    - The initial load is pretty slow. But this is probably due to the
>    fact that I am using the development server, and there are a lot of AJAX
>    requests at the same time. Since the dev server only answers one at a time,
>    it is always going to be a lot slower than the production environment.
>    - I noticed we're using decouple but there is no settings.ini example.
>    This would be useful for someone running the project for the first time.
>
> I'll keep trying it out and will also try to read the changes. Since there
> are a lot of changes, this may take some time.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/AlertaDengue/AlertaDengue/pull/29#issuecomment-184199566>
> .
>



-- 
Flávio Codeço Coelho
================
+55(21) 3799-5551
Professor
Escola de Matemática Aplicada
Fundação Getulio Vargas
Praia de Botafogo, 190 sala 312
Rio de Janeiro - RJ
22250-900
Brasil

**Comment by flavioamieiro** [comment]
@fccoelho I've made the changes necessary to deploy this new code on a Docker container. Can you please review the changes?

**Comment by fccoelho** [comment]
@flavioamieiro Everything is fine, I would just suggest to add the caching to the main view to make it faster, and then I think we can deploy.

**Comment by fccoelho** [comment]
@flavioamieiro , please check if my fix works.

**Pull request merged**
