### PR TITLE
fix(searchbox): improve searchbox speed and recognition

### LINKED ISSUE #510: Enhance Performance of City Search in Menubar Textbox
This issue focuses on optimizing the performance of the city search functionality in the menubar textbox. Currently, there might be performance issues when searching for cities, leading to delays or slow response times.

### Improve performance of city search function and remove unnecessary code:
[get_city()](https://github.com/AlertaDengue/AlertaDengue/blob/main/AlertaDengue/dados/dbdata.py#L450)

The usage of JOIN operations in the query is leading to noticeable degradation in performance, which directly impacts the overall execution speed.

This issue arises due to the involvement of a large table named "historico_alerta," resulting in a significant slowdown in query execution.

To address this performance concern, it is highly recommended to consider alternative approaches. One potential solution is leveraging a dictionary or a JSON file that contains pre-processed data of all municipalities per state. By adopting this approach, the retrieval of the required information can be expedited, leading to improved query performance.

Another effective strategy to enhance the overall result is implementing a caching mechanism like Memcache. By utilizing Memcache, the application can store frequently accessed data, resulting in improved performance and reduced database load.

If the primary objective is solely to retrieve city names based on the state, it is worth exploring these alternative solutions, as they have the potential to optimize the query execution and mitigate performance issues.

Furthermore, it is crucial to evaluate the role and functionality of the JavaScript code. It is important to determine if the code serves any essential purpose or if it can be safely removed. Conducting this evaluation will contribute to maintaining a cleaner and more efficient codebase by eliminating any unnecessary components.

*Another way to improve would be to reuse the code for searching municipalities in the [API](https://github.com/AlertaDengue/AlertaDengue/blob/main/AlertaDengue/dados/templates/services_api.html#L100).*
Screenshot_20230518_073023

### PR DESCRIPTION
**Pull request by luabida**
fix #510 

- Removed the query from postgres, passed it to a .json [file](https://github.com/AlertaDengue/AlertaDengue/blob/ee85463e9e9227299d26ccc661c14760dd0bea8c/AlertaDengue/data/municipalities.json)

### CODE REVIEW

**Review by fccoelho — APPROVED** [review]

**Comment by luabida** [comment]
I'm receiving an error using {% blocktrans %} and I couldn't find anything online, @esloch do you know anything about it?

```
    self.nodelist = self.compile_nodelist()
  File "/opt/conda/envs/alertadengue/lib/python3.10/site-packages/django/template/base.py", line 193, in compile_nodelist
    return parser.parse()
  File "/opt/conda/envs/alertadengue/lib/python3.10/site-packages/django/template/base.py", line 478, in parse
    raise self.error(token, e)
  File "/opt/conda/envs/alertadengue/lib/python3.10/site-packages/django/template/base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "/opt/conda/envs/alertadengue/lib/python3.10/site-packages/django/template/loader_tags.py", line 216, in do_block
    nodelist = parser.parse(('endblock',))
  File "/opt/conda/envs/alertadengue/lib/python3.10/site-packages/django/template/base.py", line 472, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "/opt/conda/envs/alertadengue/lib/python3.10/site-packages/django/template/base.py", line 522, in invalid_block_tag
    raise self.error(
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 6: 'blocktrans', expected 'endblock'. Did you forget to register or load this tag?
Internal Server Error: /
Traceback (most recent call last):
  File "/opt/conda/envs/alertadengue/lib/python3.10/site-packages/django/template/base.py", line 470, in parse
    compile_func = self.tags[command]
KeyError: 'blocktrans'
```

**Comment by luabida** [comment]
@fccoelho @esloch I've manually removed the `{% blocktrans %}` from the staging container so it can be tested at https://infostaging.dengue.mat.br/, please let me know if is something like this that you had in mind

**Comment by esloch** [comment]
O que nos falta aqui @luabida?

**Comment by luabida** [comment]
@esloch falta passar no CI, entrei alguma vezes no tmate mas não consegui descobrir exatamente oq houve para estar quebrando o container web.

**Comment by luabida** [comment]
@esloch I can't see relation with the error found on Tmate and this PR:

<details>
Traceback (most recent call last):
  File "/opt/conda/envs/alertadengue/lib/python3.10/site-packages/django/utils/module_loading.py", line 13, in import_string
    module_path, class_name = dotted_path.rsplit('.', 1)
ValueError: not enough values to unpack (expected 2, got 1)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/conda/envs/alertadengue/lib/python3.10/site-packages/gunicorn/workers/sync.py", line 136, in handle
    self.handle_request(listener, req, client, addr)
  File "/opt/conda/envs/alertadengue/lib/python3.10/site-packages/gunicorn/workers/sync.py", line 179, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/opt/conda/envs/alertadengue/lib/python3.10/site-packages/dj_static.py", line 83, in __call__
    return self.application(environ, start_response)
  File "/opt/conda/envs/alertadengue/lib/python3.10/site-packages/django/core/handlers/wsgi.py", line 133, in __call__
    response = self.get_response(request)
  File "/opt/conda/envs/alertadengue/lib/python3.10/site-packages/django/core/handlers/base.py", line 130, in get_response
    response = self._middleware_chain(request)
  File "/opt/conda/envs/alertadengue/lib/python3.10/site-packages/django/core/handlers/exception.py", line 49, in inner
    response = response_for_exception(request, exc)
  File "/opt/conda/envs/alertadengue/lib/python3.10/site-packages/django/core/handlers/exception.py", line 115, in response_for_exception
    log_response(
  File "/opt/conda/envs/alertadengue/lib/python3.10/site-packages/django/utils/log.py", line 224, in log_response
    getattr(logger, level)(
  File "/opt/conda/envs/alertadengue/lib/python3.10/logging/__init__.py", line 1506, in error
    self._log(ERROR, msg, args, **kwargs)
  File "/opt/conda/envs/alertadengue/lib/python3.10/logging/__init__.py", line 1624, in _log
    self.handle(record)
  File "/opt/conda/envs/alertadengue/lib/python3.10/logging/__init__.py", line 1634, in handle
    self.callHandlers(record)
  File "/opt/conda/envs/alertadengue/lib/python3.10/logging/__init__.py", line 1696, in callHandlers
    hdlr.handle(record)
  File "/opt/conda/envs/alertadengue/lib/python3.10/logging/__init__.py", line 968, in handle
    self.emit(record)
  File "/opt/conda/envs/alertadengue/lib/python3.10/site-packages/django/utils/log.py", line 122, in emit
    self.send_mail(subject, message, fail_silently=True, html_message=html_message)
  File "/opt/conda/envs/alertadengue/lib/python3.10/site-packages/django/utils/log.py", line 125, in send_mail
    mail.mail_admins(subject, message, *args, connection=self.connection(), **kwargs)
  File "/opt/conda/envs/alertadengue/lib/python3.10/site-packages/django/utils/log.py", line 128, in connection
    return get_connection(backend=self.email_backend, fail_silently=True)
  File "/opt/conda/envs/alertadengue/lib/python3.10/site-packages/django/core/mail/__init__.py", line 34, in get_connection
    klass = import_string(backend or settings.EMAIL_BACKEND)
  File "/opt/conda/envs/alertadengue/lib/python3.10/site-packages/django/utils/module_loading.py", line 15, in import_string
    raise ImportError("%s doesn't look like a module path" % dotted_path) from err
ImportError:  doesn't look like a module path
</details>

Added the EMAIL_BACKEND to console on CI to see if it helps

**Comment by esloch** [comment]
Thank you for working on these features.
Try debugging your working branch. There seems to be something that is causing a significant delay in loading all the pages of the site. 
It looks like the searchbox is displaying the entire cache list instead of the string search. 
I made a few changes to the code to adjust the colors of the datalist to match on the website. Here's an example to remove the black background color:

``` 
{% load i18n %}

<style>
    .custom-searchbox {
    position: relative;
    display: inline-block;
    width: 100%;
    }

    .custom-dropdown {
    position: absolute;
    top: 100%;
    left: 0;
    z-index: 10;
    display: none;
    width: 100%;
    background-color: blue;
    color: white;
    }

    .custom-option {
    padding: 5px;
    cursor: pointer;
    }

    .custom-option:hover {
    background-color: #003399;
    }

    .custom-option:first-child {
    border-top: none;
    }

</style>

{% load i18n %}
{% block searchbox_component %}
<div class="custom-searchbox">
  <input 
    class="form-control" 
    id="searchbar" 
    placeholder="{% blocktrans %}Encontre um município{% endblocktrans %}"
  >
  <div class="custom-dropdown">
    {% for city in options_cities %}
      <div class="custom-option" data-geocode="{{ city.geocode }}">
        {{ city.name }} - {{ city.state }}
      </div>
    {% endfor %}
  </div>
</div>

<script>
  const searchbar = document.getElementById('searchbar');
  const dropdown = document.querySelector('.custom-dropdown');
  
  // Show/hide dropdown on input focus/blur
  searchbar.addEventListener('focus', function() {
    dropdown.style.display = 'block';
  });

  searchbar.addEventListener('blur', function() {
    dropdown.style.display = 'none';
  });

  // Handle option selection
  const options = document.querySelectorAll('.custom-option');
  options.forEach(function(option) {
    option.addEventListener('click', function() {
      const geocode = this.getAttribute('data-geocode');
      if (geocode) {
        window.location.href = '/alerta/' + geocode.toString();
      }
    });
  });
</script>
{% endblock %}

```  
Screenshot_20230606_195059

**Comment by luabida** [comment]
> @esloch: I made a few changes to the code to adjust the colors of the datalist to match on the website

I've notice it doesn't use datalist, I'll check if it has the autocomplete functionality

**Comment by luabida** [comment]
Gotta find a way to:
- Define the box height
- Change the option hover color to match the blue menu 

TODO:
- Finish the redirection to the city
- Add 🔍 to the searchbox

**Comment by luabida** [comment]
clideo_editor_62a6ec564d0940d0b2732a5acc33a242

**Comment by luabida** [comment]
Both click and enter will redirect, so I don't see any reason to have a 🔍 in the box

**Comment by esloch** [comment]
Buen trabajo @luabida!

**Pull request merged**
